### ISSUE TITLE
希望添加继承缩进的功能

### ISSUE THREAD

**Issue by one-pyy** [HSwift/interactive-markdown#2]
![image](https://user-images.githubusercontent.com/72590023/215315108-add9faeb-efd8-4df3-8712-dc948f9a2367.png)
![image](https://user-images.githubusercontent.com/72590023/215315121-62d88f01-26c8-46bf-accd-2c1af8d948c6.png)
(表哥轻点打())

**Comment by HSwift** [comment]
从vscode提供的notebook的功能上看，文档块和代码块实际上是分离的，我不确定让代码块继承文档块的缩进是否合适。
![image](https://user-images.githubusercontent.com/18740745/215545679-47e619d3-b98b-49f7-a9ff-2012355cf681.png)

**Comment by one-pyy** [comment]
哇偶, 好耶
